# Rattaca rrBLUP model helper functions
#
# By: Robert Vogel
# Date: 2023-08-14


#' Predict trait values from genotype
#'
#' @description
#' The `predict_lmm` function returns the value of a 
#' quantitative trait from an animal's genotype and
#' provided parameters inferred from a reference data set.
#'
#' @export
#'
#' @param genotypes ((n sample, q markers) array | matrix) of
#'      sample genotypes.  Genotypes should be encoded 1,0,-1
#' @param u ((q markers,) vector | (q markers,1) matrix) of
#'      effect sizes for random effects
#' @param intercept (double)
#'
#' @return predictions
#
predict_lmm <- function(genotypes, u, intercept)
{
    if (!is.matrix(genotypes))
    {
        genotypes <- as.matrix(genotypes, mode="double")
    }

    if (!is.matrix(u))
    {
        u <- as.matrix(u, nrow=length(u), ncol=1, mode="double")
    }

    if (!is.matrix(intercept) || !is.vector(intercept))
    {
        intercept <- as.vector(intercept, mode="double")
    }

    if (dim(genotypes)[2] != dim(u)[1])
    {
        stop("Matrix and vector dimensions are incompatible")
    }

    tmp_predict <- drop(genotypes %*% u + intercept)

    # TODO: don't i know the type of tmp_predict?
    if (is.vector(tmp_predict))
    {
        names(tmp_predict) <- rownames(genotypes)
    }

    return(tmp_predict)
}



# TODO: Specify trait values are residuals of fixed effects.
# In documentation specify that that we assume that
# covariates have been regressed out.  Consequently, the only
# fixed effect is the intercept term

#' Fit marker based rrBLUP to data
#'
#' @description
#' Validate input data, fit LMM to data with
#' rrBLUP::mixed.solve and, and compute goodness-of-fit
#' statistics.
#'
#' @export
#' @param trait ((n animals,) double vector) of trait
#'     values.
#' @param genotypes ((n animals, q markers) double matrix)
#'     of animal genotypes.  Markers are assume to take
#'     values (1, 0, -1, NA).  NA values for marker \eqn{j} are 
#'     assigned the mean genotype over all animals \eqn{i} for
#'     for which marker \eqn{i \neq j} and is not NA.
#'
#' @return out (list): contains elements generated by
#'     rrBLUP::mixed.solve and goodness-of-fit values computed
#'     by this function.
#' \itemize{
#'      \item{$u}
#'      {
#'          ((q markers,) array) BLUPs, marker effect
#'          sizes from rrBLUP::mixed.solve
#'      }
#'      \item{$u.SE}
#'      {
#'          ((q markers,) array) standard error of 
#'          BLUPs produced by rrBLUP::mixed.solve
#'      }
#'      \item{$beta}
#'      {
#'          (double) intercept (BLUE) inferred by 
#'          rrBLUP::mixed.solve
#'      }
#'      \item{$beta.SE}
#'      {
#'          (double) standard error of intercept
#'          produced by rrBLUP::mixed.solve
#'      }
#'      \item{$LL}
#'      {
#'          (double) negative log-likelihood produced
#'          by rrBLUP::mixed.solve
#'      }
#'      \item{$Ve}
#'      {
#'          (double) variance of the error term
#'          produced by rrBLUP::mixed.solve
#'      }
#'      \item{$Vu}
#'      {
#'          (double) variance contribution of a single
#'          random effects term produced by rrBLUP::mixed.solve
#'      }
#'      \item{$r_sq}{(double) coefficient of determination}
#'      \item{$pearson_corr}{(double)}
#'      \item{$spearman_corr}{(double)}
#' }
#
fit <- function(trait, genotypes)
{
    # check data
    if (any(is.na(trait)) || any(is.na(genotypes)))
    {
        stop("Data contains NA values, check validity")
    }

    if (!is_genotype(genotypes))
    {
        stop("Not genotype data")
    }


    # TODO: check that row names match?
    out <- rrBLUP::mixed.solve(trait,
                               Z = genotypes,
                               SE = TRUE)

    tmp_predict <- predict_lmm(genotypes,
                           out$u,
                           out$beta)


    # goodness-of-fit measures
    out[["r_sq"]] <- compute_r_sq(trait, tmp_predict)
    out[["pearson_corr"]] <- cor(trait, tmp_predict,
                                 method="pearson")
    out[["spearman_corr"]] <- cor(trait, tmp_predict,,
                                  method="spearman")

    return(out)
}


#' Make a closure of the LMM
#'
#' @description
#' S
#'
#' @export
#'
#' @param intercept (double) 
#' @param u ((q markers,) vector) of BLUPs, that is the 
#'      expected value of the random marker effect sizes
#' @param int_se (NULL | double) standard deviation of the LMM
#'      random error term.
#' @param u_se (NULL | (q_markers,) vector) of stardard
#'      error of the BLUPs
#'
#' @return (function) for generating samples from genotypes
#'      under the rrBLUP LMM
#
simulator <- function(intercept, u, int_se=NULL, u_se=NULL)
{

    get_n_samples <- function(dims)
    {
        return(ifelse(is.null(dims),
                      1,
                      dims[1]))
    }

    if(is.null(u_se))
    {
        sample_generator <- function(genotypes)
        {
            return(predict_lmm(genotypes, u, intercept)
                  + rnorm(get_n_samples(dim(genotypes)), 0, sd_env))
        }
    } 
    else if(length(u) == length(u_se))
    {
        sample_generator <- function(genotypes)
        {
            return(predict_lmm(genotypes,
                           rnorm(length(u), mean=u, sd=u_se),
                           intercept)
                + rnorm(get_n_samples(dim(genotypes)), 0, sd=sd_env))
        }
    } else {
        stop("Wrong input")
    }

    return(sample_generator)
}
