# Utility functions for RATTACA
#
# By: Robert Vogel
# Date: 2023-08-20
#

#' Test whether a matrix consists of genotype data
#'
#' @description
#' Valid genotype matrices should contain values in the
#' set \eqn{\{1,0,-1\}} if no imputation performed.  Otherwise,
#' genotype values \eqn{g_{ij} \in [-1, 1]}.
#'
#' @export
#'
#' @param x ((n, m) array | vector | matrix) of genotype
#'      values
#' @param imputed_vals (boolean) whether input contains
#'      imputed values
#'
#' @return (boolean)
#
is_genotype <- function(x, imputed_vals=TRUE)
{

    if (imputed_vals)
    {
        return(all(x <= 1) && all(x >= -1))        
    } 

    return(length(setdiff(x, c(1, 0, -1))) == 0)
}


#' Load plink genotypes and perform imputation
#'
#' @export
#' @param prefix_name (character) prefix of plink
#'       bim, bed, and fam files that will be loaded
#'
#' @return ((n sample, q markers) matrix)
load_and_prepare_plink_data <- function(prefix_name)
{
    # the genotype matrix with q marker rows and
    # n sample columns
    genotypes <- genio::read_plink(prefix_name)$X - 1

    return(impute(genotypes))
}


#' load trait data from csv and set row index to given column
#'
#' @export
#'
#' @param filename (character) path to trait csv table
#' @param col_to_rownames (character) name of column whose
#'        values will be the row index names
#' @param trait_name (character) name of column whose values
#'        consists of normalized trait measurements
#' 
#' @return (dataframe)
load_and_prepare_trait_data <- function(filename,
                                        col_to_rownames,
                                        trait_name)
{
    data <- read.csv(filename)
    data <- data[!is.na(data[,trait_name]), ]

    rownames(data) <- data[, col_to_rownames]

    return(data)
}


# TODO add arg type
#' Specify command line argument values
#'
#' @export
#'
#' @param default_val (number | string) (default NULL)
#' @param help_string (string) (default NULL)
#'
#' @return (list) with correct key value pairs for parsing
#
argument <- function(default_val=NULL, help_string=NULL)
{
    return(list(val=default_val, help=help_string))
}


# TODO add type checking of argument inputs
# TODO add required specification
#' Parse command line arguments
#'
#' @export
#'
#' @param ... ((character) key = (list) value) pairs where
#'      keys are command line options (including -- prefix) in
#'      quotes, and value is a list generated by rattaca::arg
#' @param description (character)
#'
#' @return (list) ((character) key = (object)  value) from
#'      option defaults of specified values from the command
#'      line
#
argument_parser <- function(..., description=NULL)
{

    arg_defs <- list(...)

    parse_arguments <- function(args)
    {

        if (length(args) == 0 || args[1] == "--help")
        {

            if (!is.null(description))
            {
                cat(sprintf("%s\n\n",description))
            }
            
            # TODO: need a better strategy for formatting
            # argument help entries
            cat(sprintf("%s\n", "Arguments"))

            for (a in names(arg_defs))
            {
                cat(sprintf("%s\t%s\n", a, arg_defs[[a]]$help))
            }
            
            return(NULL)
        }

        arg_out <- sapply(names(arg_defs),
                          function(x) arg_defs[[x]]$val)

        i <- 1

        while (i <= length(args))
        {
            if (!(args[i] %in% names(arg_defs)))
            {
                stop("Invalid option, see --help for options") 
            }

            arg_out[[args[i]]] <- args[i+1]
            i <- i + 2
        }

        return(arg_out)
    }

    return(parse_arguments)
}
